Do not exit on exception resolving addresses to notify

Backport for 4.0.3 based upon CVE-2019-10162-4.0.7-invalidrecords.patch from upstream.

diff --git a/pdns/mastercommunicator.cc b/pdns/mastercommunicator.cc
index 82b0dbd..756eb19 100644
--- a/pdns/mastercommunicator.cc
+++ b/pdns/mastercommunicator.cc
@@ -53,6 +53,7 @@ void CommunicatorClass::queueNotifyDomain(const DNSName &domain, UeberBackend *B
   while(B->get(rr))
     nsset.insert(rr.content);
 
+  try {
   for(set<string>::const_iterator j=nsset.begin();j!=nsset.end();++j) {
     vector<string> nsips=fns.lookup(DNSName(*j), B);
     if(nsips.empty())
@@ -67,7 +68,17 @@ void CommunicatorClass::queueNotifyDomain(const DNSName &domain, UeberBackend *B
             ips.insert(caIp.toStringWithPort());
         }
       }
+    }
+  }
+  catch (PDNSException &ae) {
+    L << Logger::Error << "Error looking up name servers for " << domain << ", cannot notify: " << ae.reason << endl;
+    return;
   }
+  catch (std::exception &e) {
+    L << Logger::Error << "Error looking up name servers for " << domain << ", cannot notify: " << e.what() << endl;
+    return;
+  }
+
 
   for(set<string>::const_iterator j=ips.begin();j!=ips.end();++j) {
     L<<Logger::Warning<<"Queued notification of domain '"<<domain<<"' to "<<*j<<endl;
